enum RouteEnum {
  AccountForgotPassword = '/Account/ForgotPassword',
  AccountLogin = '/Account/Login',
  AccountResetPassword = '/Account/ResetPassword',
  AccountConfirmEmail = '/Account/ConfirmEmail',
  EstimateActual = '/estimate-actual',
  Home = '/',
  Landing = '/landing/:page',
  LandingAdmin = '/landing/admin',
  LandingReports = '/landing/reports',
  LowUtilizationReport = '/machines/LowUtilization',
  MachineDetail = '/machines/status/:machineId',
  Machines = '/machines',
  NotFoundPage = '/asdf',
  Notification = '/notification',
  NotificationRecipients = '/notification/recipients',
  NotificationSettings = '/notification/settings',
  OnTimeDelivery = '/on-time-delivery',
  OperationDetail = '/operation/detail',
  RoleManage = '/role/manage/:roleId',
  Roles = '/role',
  ScheduleDeviations = '/PriorityDeviation',
  Scheduler = '/scheduler',
  Support = '/support',
  SupportAdminTutorial = '/support/Admin',
  SupportAnalyzeTutorial = '/support/AnalyzeApp',
  SupportManageTutorial = '/support/ManageApp',
  SupportMeasureTutorial = '/support/MeasureApp',
  UserCreate = '/person/create',
  UserEdit = '/person/edit/:userId',
  Users = '/person',
  WorkOrderCreate = '/workorder/create',
  WorkOrders = '/workorder',
  WorkOrdersDelete = '/workorder/delete/:workOrderId',
  WorkOrdersDetail = '/workorder/detail/:workOrderId',
  WorkOrdersEdit = '/workorder/editWorkorder/:workOrderId',
  WorkOrdersEditOperations = '/workorder/editoperations/:workOrderId',
}

export default RouteEnum;

export const nonAuthenticatedRoutes: RouteEnum[] = [
  RouteEnum.AccountLogin,
  RouteEnum.AccountForgotPassword,
  RouteEnum.AccountResetPassword,
  RouteEnum.AccountConfirmEmail,
];
